name: Feature request
description: Suggest an improvement or new feature for DRH - Object Layout Studio.
title: "[Feature]: "
labels:
  - feature request
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting an improvement for DRH - Object Layout Studio.

  - type: dropdown
    id: edition
    attributes:
      label: Edition
      options:
        - Complete - DRH - Object Layout Studio
        - Lite - DRH - Object Layout Studio Lite
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
    validations:
      required: true

  - type: textarea
    id: proposed_solution
    attributes:
      label: Proposed solution
    validations:
      required: true

  - type: textarea
    id: workflow_benefit
    attributes:
      label: Workflow benefit
    validations:
      required: true
